// scripts\seed\users.js
import bcrypt from "bcrypt";

const admin = {
    username: process.env.ADMIN_NAME,
    email: process.env.ADMIN_EMAIL,
    hashed_password: await bcrypt.hash(process.env.ADMIN_PASSWORD, 10),
    role: "Admin",
    lastLogin: null,
    lastAccess: null,
    lastPasswordReset: null,
    createdAt: null,
    createdBy: null,
    updatedAt: null,
    updatedBy: null,
    seededAt: new Date(),
    isActive: true,
};

export default [
    { ...admin },
    {
        username: "Guna",
        email: process.env.ADMIN_EMAIL,
        hashed_password: await bcrypt.hash("Guna@123", 10),
        role: "Manager",
        lastLogin: null,
        lastAccess: null,
        lastPasswordReset: null,
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        seededAt: new Date(),
        isActive: true,
    },
    {
        username: "Nataraj",
        email: process.env.ADMIN_EMAIL,
        hashed_password: await bcrypt.hash("Nataraj@123", 10),
        role: "Manager",
        lastLogin: null,
        lastAccess: null,
        lastPasswordReset: null,
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        seededAt: new Date(),
        isActive: true,
    },
    {
        username: "VJ",
        email: process.env.ADMIN_EMAIL,
        hashed_password: await bcrypt.hash("VJ@123", 10),
        role: "Manager",
        lastLogin: null,
        lastAccess: null,
        lastPasswordReset: null,
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        seededAt: new Date(),
        isActive: true,
    },
    {
        username: "Seeni",
        email: process.env.ADMIN_EMAIL,
        hashed_password: await bcrypt.hash("Seeni@123", 10),
        role: "Manager",
        lastLogin: null,
        lastAccess: null,
        lastPasswordReset: null,
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        seededAt: new Date(),
        isActive: true,
    },
    {
        username: "Sara",
        email: process.env.ADMIN_EMAIL,
        hashed_password: await bcrypt.hash("Sara@123", 10),
        role: "Manager",
        lastLogin: null,
        lastAccess: null,
        lastPasswordReset: null,
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        seededAt: new Date(),
        isActive: true,
    },
    {
        username: "Ramki",
        email: process.env.ADMIN_EMAIL,
        hashed_password: await bcrypt.hash("Ramki@123", 10),
        role: "Manager",
        lastLogin: null,
        lastAccess: null,
        lastPasswordReset: null,
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        seededAt: new Date(),
        isActive: true,
    },
];
